/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.secureinfosoft.student;


import java.security.MessageDigest;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.UUID;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.secureinfosoft.java.MD5password;
import com.secureinfosoft.java.Mail;
import com.secureinfosoft.java.StudentRegistration;

/** 
 * MyEclipse Struts
 * Creation date: 02-02-2014
 * 
 * XDoclet definition:
 * @struts.action path="/studentRegistration" name="studentRegistrationForm" input="student/studentRegistration.jsp" scope="request" validate="true"
 */
public class StudentRegistrationAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StudentRegistrationForm studentRegistrationForm = (StudentRegistrationForm) form;// TODO Auto-generated method stub
		
		String nm = studentRegistrationForm.getName();
		String em = studentRegistrationForm.getEmail();
		String dp = studentRegistrationForm.getDepartment();
		String ps = studentRegistrationForm.getCpass();
		String ph = studentRegistrationForm.getPhone();
		String uu = null;
		String passwd = null;
		UUID idone = UUID.randomUUID();
		uu = idone.toString();
		
		DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
		Date dd = new Date();
		String date = df.format(dd);
		String protocol = "0";
		
		try
		{
		MessageDigest md=MessageDigest.getInstance("MD5");
		String input=ps;
		md.update(input.getBytes());
		byte[] output=md.digest();
		MD5password sd = new MD5password();
		passwd=sd.bytesToHex(output);
		}
		catch(Exception e)
		{
			System.out.println(e.getMessage());
		}
		
		
		
					
		
		
		boolean heli = StudentRegistration.check(em);
		
		if(heli == true)
		{
			boolean badi = StudentRegistration.emailme(em, uu);
			if(badi == true)
			{
			int status = StudentRegistration.insert(nm, em, passwd, dp, ph, uu, protocol, date);
			
				if(status>0)
				{
					return mapping.findForward("success");
				}
				else
				{
					return mapping.findForward("failure");
				 }
			}
				else
				{
					return mapping.findForward("failure");
				}
			}
		
		
		return mapping.findForward("failure");
		
		
	
	}
}