/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.secureinfosoft.admin;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-02-2014
 * 
 * XDoclet definition:
 * @struts.action path="/administratorLogin" name="administratorLoginForm" input="admin/administratorLogin.jsp" scope="request" validate="true"
 */
public class AdministratorLoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdministratorLoginForm administratorLoginForm = (AdministratorLoginForm) form;// TODO Auto-generated method stub
		
		
		String id = administratorLoginForm.getLoginid();
		String pass = administratorLoginForm.getPasswd();
		
		
		if(id.equals("gateempowerment@gmail.com") && pass.equals("uvpce@123"))
		{
			
			HttpSession admin = request.getSession();
			admin.setAttribute("email", id);
			return mapping.findForward("success");
		}
		
		
		
		return mapping.findForward("failure");
	}
}