/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.secureinfosoft.admin;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;

import com.secureinfosoft.Hibernate.HibernateUtil;
import com.secureinfosoft.java.DepartmentAdd;

/** 
 * MyEclipse Struts
 * Creation date: 02-02-2014
 * 
 * XDoclet definition:
 * @struts.action path="/departmentAddd" name="departmentAdddForm" input="admin/departmentAddd.jsp" scope="request" validate="true"
 */
public class DepartmentAdddAction extends Action {
	/*
	 * Generated Methods
	 */

   
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DepartmentAdddForm departmentAdddForm = (DepartmentAdddForm) form;// TODO Auto-generated method stub
		
		String dep = departmentAdddForm.getDepartment();
		
		boolean heli = DepartmentAdd.check(dep);
		
		if(heli == true)
		{
		
		int status = DepartmentAdd.insert(dep);
		
		if(status>0)
		{
			return mapping.findForward("success");
		}
		}
		
		return mapping.findForward("failure");
	}
}