/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.secureinfosoft.admin;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.secureinfosoft.Hibernate.HibernateUtil;
import com.secureinfosoft.Hibernate.UserLogPOJO;

/** 
 * MyEclipse Struts
 * Creation date: 02-12-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class DisplayUserLogsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		String wh = "0";
		Session session = HibernateUtil.getSessionFactory().openSession();
		Transaction t = session.beginTransaction();
		Query q = session.createQuery("From UserLogPOJO where who = :w");
		q.setString("w",wh );
		List<UserLogPOJO> l = (List<UserLogPOJO>)q.list();
		
		request.getSession().setAttribute("data", l);
		
		t.commit();
		
	
		
		
		return mapping.findForward("success");
	}
}