/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.secureinfosoft.admin;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.secureinfosoft.Hibernate.HibernateUtil;
import com.secureinfosoft.Hibernate.StudentMarksPOJO;

/** 
 * MyEclipse Struts
 * Creation date: 02-12-2014
 * 
 * XDoclet definition:
 * @struts.action path="/search_DisplayUserMarks" name="search_DisplayUserMarksForm" input="admin/search_DisplayUserMarks.jsp" scope="request" validate="true"
 */
public class Search_DisplayUserMarksAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Search_DisplayUserMarksForm search_DisplayUserMarksForm = (Search_DisplayUserMarksForm) form;// TODO Auto-generated method stub
		
		
		String type1 = "chapter-wise";
		String type2 = "subject-wise";
		
		String _search = search_DisplayUserMarksForm.getSearch();
		
		
		Session sess = HibernateUtil.getSessionFactory().openSession();
		Transaction t = sess.beginTransaction();
		
		
		if(_search.equals("chapter-wise"))
		{
			Query q = sess.createQuery("From StudentMarksPOJO where type = :t");
			q.setString("t",type1);
			List<StudentMarksPOJO> l = (List<StudentMarksPOJO>)q.list();
			
			
			HttpSession admin = request.getSession();
			admin.setAttribute("type", "chapter-wise");
			
			request.getSession().setAttribute("data", l);
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("subject-wise"))
		{
			Query q = sess.createQuery("From StudentMarksPOJO where type = :t");
			q.setString("t",type2);
			List<StudentMarksPOJO> l = (List<StudentMarksPOJO>)q.list();
			
			HttpSession admin = request.getSession();
			admin.setAttribute("type", "subject-wise");
			
			request.getSession().setAttribute("data", l);
			
			return mapping.findForward("success");
		}
		Query q = sess.createQuery("From StudentMarksPOJO where type = :t");
		q.setString("t","general");
		List<StudentMarksPOJO> l = (List<StudentMarksPOJO>)q.list();
		
		HttpSession admin = request.getSession();
		admin.setAttribute("type", "general");
		
		request.getSession().setAttribute("data", l);
		
		return mapping.findForward("success");
		
	}
}