/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.secureinfosoft.admin;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.secureinfosoft.Hibernate.HibernateUtil;
import com.secureinfosoft.Hibernate.UserLogPOJO;

/** 
 * MyEclipse Struts
 * Creation date: 02-12-2014
 * 
 * XDoclet definition:
 * @struts.action path="/search_DisplayUserLogs" name="search_DisplayUserLogsForm" input="admin/search_DisplayUserLogs.jsp" scope="request" validate="true"
 */
public class Search_DisplayUserLogsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Search_DisplayUserLogsForm search_DisplayUserLogsForm = (Search_DisplayUserLogsForm) form;// TODO Auto-generated method stub
		
		
		String _search = search_DisplayUserLogsForm.getSearch();
		String _value = search_DisplayUserLogsForm.getValue();
		String wh="0";
		
		
		Session sess = HibernateUtil.getSessionFactory().openSession();
		Transaction t = sess.beginTransaction();
		
		
		if(_search.equals("Name"))
		{
			Query q = sess.createQuery("From UserLogPOJO where name = :n and who = :w");
			q.setString("n", _value);
			q.setString("w",wh );
			List<UserLogPOJO> l = (List<UserLogPOJO>)q.list();
			
			request.getSession().setAttribute("data", l);
			
			return mapping.findForward("success");
			
			
			
		}
		else if(_search.equals("Email"))
		{
			
			Query q = sess.createQuery("From UserLogPOJO where email = :n and who = :w");
			q.setString("n", _value);
			q.setString("w",wh );
			List<UserLogPOJO> l = (List<UserLogPOJO>)q.list();
			
			request.getSession().setAttribute("data", l);
			
			return mapping.findForward("success");
			
		}
		
		Query q = sess.createQuery("From UserLogPOJO where department = :n and who = :w");
		q.setString("n", _value);
		q.setString("w",wh );
		List<UserLogPOJO> l = (List<UserLogPOJO>)q.list();
		
		request.getSession().setAttribute("data", l);
		
		return mapping.findForward("success");
		
		
	}
}