/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.secureinfosoft.admin;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.secureinfosoft.Hibernate.HibernateUtil;
import com.secureinfosoft.Hibernate.StudentPOJO;

/** 
 * MyEclipse Struts
 * Creation date: 02-12-2014
 * 
 * XDoclet definition:
 * @struts.action path="/search_DisplayUser" name="search_DisplayUserForm" input="admin/search_DisplayUser.jsp" scope="request" validate="true"
 */
public class Search_DisplayUserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Search_DisplayUserForm search_DisplayUserForm = (Search_DisplayUserForm) form;// TODO Auto-generated method stub
		
		String search = search_DisplayUserForm.getSearch();
		System.out.println(search);
		
		Session sess = HibernateUtil.getSessionFactory().openSession();
		Transaction t = sess.beginTransaction();
		Query q = sess.createQuery("From StudentPOJO where department = :d");
		q.setString("d",search);
		List<StudentPOJO> l = (List<StudentPOJO>)q.list();
		request.getSession().setAttribute("data",l);
		t.commit();
		sess.close();
		
		return mapping.findForward("success");
		
	}
}